name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-13  # Mac runner con Xcode

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Dar permisos de ejecuci√≥n al script
        run: chmod +x ./run_tests.sh
        
      - name: üìÇ Mostrar estructura del repositorio
        run: |
          echo "Contenido en la ra√≠z del repositorio:"
          ls -l
          echo "Contenido dentro de InnovaFit:"
          ls -l InnovaFit || echo "‚ùå No existe carpeta 'InnovaFit'"
          echo "Contenido dentro de InnovaFit.xcodeproj:"
          ls -l InnovaFit.xcodeproj || echo "‚ùå No existe 'InnovaFit.xcodeproj'"

      - name: Ejecutar pruebas
        run: ./run_tests.sh




